#DB
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    #redis
  redis:
    host: rayfoo.cn
    port: 6379
page:
  rows: 50
